package fr.jl.boundaries;

import fr.jl.entities.Globale;
import java.sql.Connection;

/**
 *
 * @author Jessica
 */
public class JifAjouter extends javax.swing.JInternalFrame {

    private Connection cnx;
    
    /**
     * Creates new form JifAjouter
     */
    public JifAjouter() {
        initComponents();
        // Titre de la fenetre
        setTitle("Ajouter un film");
        // Ouverture de la fenetre en premier plan
        setVisible(true);
        // Connexion à la BD
        cnx = Globale.getCnx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
