package fr.jl.boundaries;

import fr.jl.daos.RealisateurDAO;
import fr.jl.entities.Globale;
import fr.jl.entities.Realisateur;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jessica
 */
public class JifRealisateurs extends javax.swing.JInternalFrame {

    private Connection cnx;
    private DefaultTableModel ldtm;
    
    /**
     * Creates new form JifAjouter
     */
    public JifRealisateurs() {
        initComponents();
        // Titre de la fenetre
        setTitle("Realisateurs");
        // Ouverture de la fenetre en premier plan
        setVisible(true);
        // Taille de la fenetre
        setSize(975, 500);
        // Connexion à la BD
        cnx = Globale.getCnx();
        // Affichage de la table réalisateur dans la jTable
        try {
            // Recuperation du modèle de la jTable
            ldtm = (DefaultTableModel) jTableRealisateurs.getModel();
        } catch (Exception ex) {
            jLabelMessage.setText(ex.getMessage());
        }
        // Remplissage tableau
        getRealisators();
    }
    
    // Affichage de tous les réalisateurs dans la jTable
    private void getRealisators() {
        // Initialisation de la jTable à 0 en partant de la fin
        for (int i = ldtm.getRowCount() - 1; i >= 0; i--) {
            ldtm.removeRow(i);
        }
        try {
            // Déclaration de l'utilisation d'un tableau d'objet
            Object[] tLigne;
            // Déclaration de l'utilisation d'un objet DAO
            RealisateurDAO dao = new RealisateurDAO(cnx);
            // Récupération du résultat du selectAll dans une liste
            List<Realisateur> liste = dao.selectAll();
            // Parcours de la liste
            for (int i = 0; i < liste.size(); i++) {
                // Récupération des valeurs de i dans la liste
                Realisateur realisateur = liste.get(i);
                // Définition du nombre d'objets dans le tableau
                tLigne = new Object[1];
                // Récupération des valeurs trouvées
                tLigne[0] = realisateur.getNomRealisateur();
                // Ajout des valeurs trouvées dans la jTable
                ldtm.addRow(tLigne);
            }
            // Calcul du nombre de lignes dans la jTable
            int nbLigne = ldtm.getRowCount();
            // Affichage du nombre de ligne dans le jLabel
            jLabelMessage.setText("Nombre de réalisateurs : " + Integer.toString(nbLigne));
        } catch (Exception e) {
            System.out.println(e.getMessage());
            // Affichage d'une boite de dialogue indiquant l'erreur
            JOptionPane message;
            message = new JOptionPane();
            message.showMessageDialog(null, "Erreur de chargement de la base de donnée", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMessage = new javax.swing.JLabel();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jTextFieldRealisateur = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRealisateurs = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jTextFieldRealisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRealisateurActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jLabel1.setText("Realisateur :");

        jTableRealisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Realisateur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRealisateurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRealisateursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRealisateurs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRealisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupprimer))
                    .addComponent(jLabelMessage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRealisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMessage)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // Suppression d'un realisateur
        // Test si une ligne est bien selectionnée
        if (jTextFieldRealisateur.getText().isEmpty()) {
            // Affichage d'une boite de dialogue indiquant l'erreur
            JOptionPane message;
            message = new JOptionPane();
            message.showMessageDialog(null, "Vous devez selectionner un réalisateur", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            // Suppression du réalisateur selectionné
            try {
                // Déclaration de l'utilisation d'un objet DAO
                RealisateurDAO dao = new RealisateurDAO(cnx);
                // Récupération de la valeur du champs
                Realisateur r = new Realisateur(jTextFieldRealisateur.getText());
                // Suppression de la valeur
                dao.delete(r);
                // Execution dans la base de données
                cnx.commit();
                // Remise à zéro du champs
                jTextFieldRealisateur.setText("");
                // Maj tableau
                getRealisators();
            } catch (Exception e) {
                System.out.println(e.getMessage());
                // Affichage d'une boite de dialogue indiquant l'erreur
                JOptionPane message;
                message = new JOptionPane();
                message.showMessageDialog(null, "Erreur lors de la suppression", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // Modification d'un réalisateur
        // Test si une ligne est bien selectionnée
        if (jTextFieldRealisateur.getText().isEmpty()) {
            // Affichage d'une boite de dialogue indiquant l'erreur
            JOptionPane message;
            message = new JOptionPane();
            message.showMessageDialog(null, "Vous devez selectionner un réalisateur", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                // Déclaration de l'utilisation d'un objet DAO
                RealisateurDAO dao = new RealisateurDAO(cnx);
                // Recupération du numéro de la ligne selectionnée
                int LiSelectionnee = jTableRealisateurs.getSelectedRow();
                // Récupération de la valeur dans la ligne selectionnée
                String lsRealisateur = jTableRealisateurs.getValueAt(LiSelectionnee, 0).toString();
                // Récupération du réalisateur selectionné
                Realisateur realisateur = dao.selectOne(lsRealisateur);
                // Récupération de la valeur du champs
                Realisateur r = new Realisateur(realisateur.getIdRealisateur(), jTextFieldRealisateur.getText());
                // Modification de la valeur
                dao.update(r);
                // Execution dans la base de données
                cnx.commit();
                // Remise à zéro du champs
                jTextFieldRealisateur.setText("");
                // Maj tableau
                getRealisators();
            } catch (Exception e) {
                System.out.println(e.getMessage());
                // Affichage d'une boite de dialogue indiquant l'erreur
                JOptionPane message;
                message = new JOptionPane();
                message.showMessageDialog(null, "Erreur lors de la modification", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // Ajout d'un réalisateur
        // Test si le champs est vide
        if (jTextFieldRealisateur.getText().isEmpty()) {
            // Affichage d'une boite de dialogue indiquant l'erreur
            JOptionPane message;
            message = new JOptionPane();
            message.showMessageDialog(null, "Veuillez saisir le nom d'un réalisateur", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                // Déclaration de l'utilisation d'un objet DAO
                RealisateurDAO dao = new RealisateurDAO(cnx);
                // Récupération de la valeur du champs
                Realisateur r = new Realisateur(jTextFieldRealisateur.getText());
                // Ajout de la valeur
                dao.insert(r);
                // Execution dans la base de données
                cnx.commit();
                // Remise à zéro du champs
                jTextFieldRealisateur.setText("");
                // Maj tableau
                getRealisators();
            } catch (Exception e) {
                System.out.println(e.getMessage());
                // Affichage d'une boite de dialogue indiquant l'erreur
                JOptionPane message;
                message = new JOptionPane();
                message.showMessageDialog(null, "Erreur lors de l'ajout", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jTableRealisateursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRealisateursMouseClicked
        // Recupération du numéro de la ligne selectionnée
        int LiSelectionnee = jTableRealisateurs.getSelectedRow();
        // Récupération de la valeur dans la ligne selectionnée
        String lsRealisateur = jTableRealisateurs.getValueAt(LiSelectionnee, 0).toString();
        // Insertion de la valeur de la ligne selectionnée dans le champs
        jTextFieldRealisateur.setText(lsRealisateur);
    }//GEN-LAST:event_jTableRealisateursMouseClicked

    private void jTextFieldRealisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRealisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRealisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRealisateurs;
    private javax.swing.JTextField jTextFieldRealisateur;
    // End of variables declaration//GEN-END:variables
}
